name: fl_animated_linechart
description: Animated flutter linechart
version: 0.0.1
author: Jacob Just
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
